### ISSUE TITLE
Name issue with Vasa Nistirio

### ISSUE THREAD

**Issue by EnuDelrum** [XrioBtw/npc-id#2]
In Chambers of Xeric, when you first see Vasa Nistirio and he's still a pile of rocks, his name is "Rocks". The problem is what's displayed above his head is:
**<col=ooffff>Rocks</col>**
![Bug](https://github.com/XrioBtw/npc-id/assets/128336524/3b4a1687-f5cb-4654-863b-7f8902d012cc)

**Comment by XrioBtw** [comment]
I have now fixed this by adding a config option `Strip tags` which removes everything surrounded by `<` and `>`. The updated plugin version 1.3.1 is now live in the client.
