### ISSUE TITLE
Settings Request: Blacklist Specific NPCs

### ISSUE THREAD

**Issue by F5in** [XrioBtw/npc-id#3]
I use this addon to show names above NPCs heads, however there doesn't seem to be any way to have it only on for certain NPCs. I would like the option to blacklist things that I have hidden via Entity Hider, such as pets or random events.

Just a picture of what I'm talking about, thanks for reading.
![image](https://github.com/XrioBtw/npc-id/assets/38023683/2c5275fe-1e72-42df-8a46-d52e7926187e)

**Comment by XrioBtw** [comment]
Options to hide pets and random events have now been added in version 1.3.2
